services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false   # disattiva autenticazione (solo per test!)
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data


  carmate:
    build:
      context: ./
    volumes:
      - ./:/carmate
    container_name: carmate
    environment:
      - ELASTIC_HOST=http://elasticsearch:9200
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
    depends_on:
      - elasticsearch
    ports:
      - "8501:8501"
    restart: unless-stopped
    command: streamlit run /carmate/streamlit_app.py --server.port=8501 --server.address=0.0.0.0

volumes:
  esdata:
    driver: local  